#title: Umme Munira
#logo:
#description: Welcome! Explore three sections: Byte-Sized Data Interview for actionable data interview tips, Generative AI and LLM Projects showcasing my analytics work, and SupplySenseAI highlighting AI-driven supply chain projects. Discover, learn, and get inspired by the power of data science and AI.
#show_downloads: true
navigation:
  - title: "Home"
    url: /
  - title: "Byte-Sized Data Interview"
    url: /data-interview
  - title: "Generative AI and LLM Projects"
    url: /generative-ai
  - title: "SupplySenseAI"
    url: /supply-sense-ai
theme: jekyll-theme-slate
