title: My Website
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ummeamunira.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-slate # replace with your chosen theme

navigation:
  - title: "Home"
    url: /
  - title: "Byte-Sized Data Interview"
    url: /data-interview/
  - title: "Analytics and GenAI"
    url: /analytics/
  - title: "SupplySenseAI"
    url: /supply-sense-ai/

